-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ
    START WITH 10 -- 시작 번호 (기본값:1)
    INCREMENT BY -1 -- 증가 값 (기본값:1)
    MAXVALUE 9999 -- 최대값
    MINVALUE -9999 --최소값
    NOCYCLE         -- 순환 금지
    NOCACHE;         -- 캐시메모리 사용안 함
    
SELECT FRIEND_SQ.NEXTVAL FROM DUAL; --DUAL: 오라클이 제공해주는 테이블
                                    --NEXVAL: 순차번호생성
SELECT FRIEND_SQ.CURRVAL FROM DUAL; -- CURRVAL: 현재까지 진행된 순차번호

--EX. 시퀀스를 이용한 FRIEND 테이블
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR(255),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '신림'); -- 여러번 실행 가능

SELECT NO, NAME, TEL, ADDRESS, TO_CHAR(LAST_MODIFY, 'RR/MM/DD AM HH:MI:SS') 
    FROM FRIEND;
    
INSERT INTO FRIEND
    VALUES (FRIEND_SQ.NEXTVAL, '김길동', '010-9999-9999', '봉천', SYSDATE);
    
-- 연습문제 (요구사항을 만족하는 데이터베이스를 설계하고, 테이블을 생성, 데이터를 입력하는 SQL문을 조건에 맞게 작성하시오.)
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

--테이블 생성
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(3) PRIMARY KEY,
    LEVELNAME VARCHAR2(30) NOT NULL
);
DESC MEMBER_LEVEL;

CREATE TABLE MEMBER(
    mNO NUMBER(4) PRIMARY KEY,
    mNAME VARCHAR2(20) NOT NULL,
    mPW VARCHAR2(8) NOT NULL,
    mEMAIL VARCHAR(50) UNIQUE,
    mPOINT NUMBER(9) CHECK(mPOINT>=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(3) REFERENCES MEMBER_LEVEL(LEVELNO)
);
DESC MEMBER;

-- mNO를 위한 SEQUENCE 생성
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
    MAXVALUE 9999 NOCACHE NOCYCLE;

--데이터 입력
INSERT INTO MEMBER_LEVEL VALUES(-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES(0, '일반');
INSERT INTO MEMBER_LEVEL VALUES(1, '실버');
INSERT INTO MEMBER_LEVEL VALUES(2, '골드');
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '24/09/26', 0);
INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 0, '22/04/01', 1);
SELECT * FROM MEMBER;

--데이터 출력
SELECT mNO, mNAME, mRDATE, mEMAIL, mPOINT "point", LEVELNAME||'고객' "levelname" FROM MEMBER M, MEMBER_LEVEL ML
    WHERE M.LEVELNO=ML.LEVELNO;
