-- c:/ai/source/01_python/ch15.sql
-- 테이블생성 (NAME, TEL, EMAIL, AGE, GARDE, ETC)
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    NAME VARCHAR2(20),
    TEL VARCHAR2(20),
    EMAIL VARCHAR2(30) UNIQUE,
    AGE NUMBER(3),
    GRADE NUMBER(1) CHECK(GRADE BETWEEN 1 AND 5),
    ETC VARCHAR(100)
);
-- 1번 입력
INSERT INTO MEMBER VALUES ('홍길동', '010-9999-9999', 'H@H.COM', 33, 2, '까칠해');

--2번 전체 조회
SELECT * FROM MEMBER ORDER BY NAME;

--3번 이름 차직
SELECT * FROM MEMBER WHERE NAME='홍길동';

--4번 메일 삭제
DELETE FROM MEMBER WHERE EMAIL='H@H.COM';

COMMIT;